### PR TITLE
Fixed #72 - Incorrect runner behavior when tests list is empty

### LINKED ISSUE #72: Incorrect runner behavior when tests list is empty
1) `runner.src([]).run()` - should not open a browser until all tests are not compiled. Because if compilation fails we end up with the hanging open local browser connections.
2) `runner.src(someTests).filter(()=>false).run()` - runner crashes with a js error now

### PR DESCRIPTION
**Pull request by AndreyBelym**

### CODE REVIEW

**Comment by inikulin** [comment]
Tests fail

**Comment by AndreyBelym** [comment]
FPR

File: src/runner/bootstrapper.js [hunk 1]
```diff
@@ -74,6 +74,9 @@ export default class Bootstrapper {
         if (!this.browsers.length)
             throw new Error(getText(MESSAGE.browserNotSet));
 
+        if (this.browsers.some(browser => browser instanceof BrowserConnection && browser.disconnected))
```
Comment (inikulin) [inline src/runner/bootstrapper.js]: We can move this check below, to avoid check for `BrowserConnection` instance.

File: src/runner/index.js [hunk 2]
```diff
@@ -33,6 +35,13 @@ export default class Runner {
     // Run task
     _runTask (Reporter, browserConnections, tests) {
         return new Promise((resolve, reject) => {
+            if (browserConnections.some(connection => connection.disconnected)) {
```
Comment (inikulin) [inline src/runner/index.js]: AFAIK we don't need this check here, because `_runTask` call happens synchronously right after the browser bootstrapping

File: src/runner/bootstrapper.js [hunk 3]
```diff
@@ -74,6 +74,9 @@ export default class Bootstrapper {
...
+            throw new Error(getText(MESSAGE.cantEstablishBrowserConnection));
```
Comment (inikulin) [inline src/runner/bootstrapper.js]: We need another message here. We don't try to establish connection, we have a connection passed which is already disconnected.

**Comment by inikulin** [comment]
\r-

**Comment by AndreyBelym** [comment]
FPR

File: src/browser-connection/index.js [hunk 4]
```diff
@@ -34,12 +35,16 @@ export default class BrowserConnection extends EventEmitter {
         this.idleUrl      = `${gateway.domain}/browser/idle/${this.id}`;
         this.statusUrl    = `${gateway.domain}/browser/status/${this.id}`;
 
+        this.on('error', () => {
+            this.disconnected = true;
```
Comment (inikulin) [inline src/browser-connection/index.js]: We should set this flag in `close` function. Because currently I can manually close connection and pass it to the runner and it will not cause early error.

File: src/messages.js [hunk 5]
```diff
@@ -1,9 +1,11 @@
 export const MESSAGE = {
     browserDisconnected:            'The {userAgent} browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.',
+    browsersDisconnected:           'The following browsers disconnected: {userAgents}. This problem may appear when a browser hangs or is closed, or due to network issues.',
```
Comment (inikulin) [inline src/messages.js]: I think it should be something like `cantRunOnDisconnectedBrowsers` and the text should be appropriate, something like: 'Can't run tests on disconnected browsers'. @VasilyStrelyaev will help with message.

File: src/messages.js [hunk 6]
```diff
@@ -1,9 +1,11 @@
...
     cantEstablishBrowserConnection: 'Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.',
     cantFindBrowserForAlias:        'Cannot find a corresponding browser for the following alias: {alias}.',
     browserNotSet:                  'No browser selected to test against. Use the Runner.browsers() method to specify the target browser.',
     testSourcesNotSet:              'No test file specified. Use the Runner.src() function to specify one or several test files to run.',
+    testsAreNotFound:               'No tests were found. Either the test files contain no tests or the filter function is too restrictive.',
```
Comment (inikulin) [inline src/messages.js]: It's better `noTestsToRun`. I don't like the first sentence as well: found there? It's better: 'No tests were set to run' or smthg. \cc @VasilyStrelyaev

File: src/runner/bootstrapper.js [hunk 7]
```diff
@@ -77,14 +77,29 @@ export default class Bootstrapper {
...
             browserConnections.forEach(bc => {
                 if (bc instanceof LocalBrowserConnection)
                     bc.close();
             });
+        }
+
+        var disconnectedUserAgents = browserConnections.filter(bc => bc.disconnected).map(bc => bc.userAgent);
+
+        if (disconnectedUserAgents.length) {
+            closeLocalConnections();
```
Comment (inikulin) [inline src/runner/bootstrapper.js]: I haven't figured out that we will need to close local connections. From this perspective previous code was much better. So, let's roll it back. Sorry for that.

File: test/server/runner-test.js [hunk 8]
```diff
@@ -138,8 +138,73 @@ describe('Runner', function () {
...
+
+            runner.
+                browsers(brokenConnection)
+                .reporter('list')
+                .src('test/server/data/test-suite/top.test.js');
+
+            brokenConnection.emit('error', 'It happened');
+        });
+
+        it('Should raise error if multiple browsers disconnected before bootstrapping', function (done) {
```
Comment (inikulin) [inline test/server/runner-test.js]: Is there any difference between this and previous test? Seems like they test the same scenario

File: test/server/runner-test.js [hunk 9]
```diff
@@ -248,6 +313,53 @@ describe('Runner', function () {
                 })
                 .catch(done);
         });
+
+        it('Should not create a new local browser connection if sources are empty', function (done) {
+            var startConnectionID = testCafe.createBrowserConnection().id;
```
Comment (inikulin) [inline test/server/runner-test.js]: `ID` shouldn't be all upper case: `Id`. It's more likely `firstConnectionId`, BTW @VasilyStrelyaev check test names, please

File: test/server/runner-test.js [hunk 10]
```diff
@@ -325,4 +437,39 @@ describe('Runner', function () {
             testFilter(filter, expectedTestNames, done);
         });
     });
+
+    describe('.run()', function () {
```
Comment (inikulin) [inline test/server/runner-test.js]: All bootstrapping-related tests should be in this section, because bootstrapping happens on `run`.

File: test/server/runner-test.js [hunk 11]
```diff
@@ -325,4 +437,39 @@ describe('Runner', function () {
...
+                    throw new Error('Promise rejection expected');
+                })
+                .catch(function (err) {
+                    expect(err.message).eql('I have failed :(');
+                });
+
+            setTimeout(function () {
+                var status = brokenConnection.getStatus();
+
+                expect(status.cmd).eql(COMMAND.run);
```
Comment (inikulin) [inline test/server/runner-test.js]: We shouldn't assert status here, we need to repeat timeout until we will not get `COMMAND.run`, then emit error

File: test/server/runner-test.js [hunk 12]
```diff
@@ -248,6 +313,53 @@ describe('Runner', function () {
...
+                .src('test/server/data/test-suite/top.test.js')
+                .filter(function () {
+                    return false;
+                })
+                .run()
+                .then(function () {
+                    throw new Error('Promise rejection expected');
+                })
+                .catch(function (err) {
+                    expect(err.message).eql('No tests were found. Either the test files contain no tests or the filter function is too restrictive.');
```
Comment (inikulin) [inline test/server/runner-test.js]: Split long strings using concat

**Comment by inikulin** [comment]
\r-

File: src/messages.js (hunk 6 above)
Comment (VasilyStrelyaev) [inline src/messages.js]: I like the name `noTestsToRun`, and I'd use it as the first sentence.
`No tests to run. Either the test files contain no tests or the filter function is too restrictive.`

File: src/messages.js (hunk 5 above)
Comment (VasilyStrelyaev) [inline src/messages.js]: I feel like the fact that you can't run tests against disconnected browsers is a truism, though it fits well as a property name. So, I would go for something like:
`cantRunAgainstDisconnectedBrowsers: 'The following browsers disconnected: {userAgents}. Tests won't be run. This problem may appear when a browser hangs or is closed, or due to network issues.',`

Comment (inikulin) [inline src/messages.js]: I don't like ` This problem may appear when a browser hangs or is closed, or due to network issues.` part here. They may be disconnected if you just called `bc.close()`.

Comment (VasilyStrelyaev) [inline src/messages.js]: okay then, the final (and checked) version:
`cantRunAgainstDisconnectedBrowsers: 'The following browsers disconnected: {userAgents}. Tests won't be run.',`

File: test/server/runner-test.js [hunk 13]
```diff
@@ -138,8 +138,73 @@ describe('Runner', function () {
                 .catch(done);
         });
 
+        it('Should raise error if browser disconnected before bootstrapping', function (done) {
```
Comment (VasilyStrelyaev) [inline test/server/runner-test.js]: Should raise an error if the browser disconnects before bootstrapping

File: test/server/runner-test.js (hunk 8 above)
Comment (VasilyStrelyaev) [inline test/server/runner-test.js]: Should raise an error if multiple browsers get disconnected before bootstrapping

File: test/server/runner-test.js [hunk 14]
```diff
@@ -138,8 +138,73 @@ describe('Runner', function () {
...
+            runner.
+                browsers(brokenConnection1, brokenConnection2)
+                .reporter('list')
+                .src('test/server/data/test-suite/top.test.js');
+
+            brokenConnection1.emit('error', 'It happened');
+            brokenConnection2.emit('error', 'It happened');
+        });
+
         it('Should raise error if the browser connections are not ready', function (done) {
```
Comment (VasilyStrelyaev) [inline test/server/runner-test.js]: an error
(while I'm hunting for articles)

File: test/server/runner-test.js [hunk 15]
```diff
@@ -248,6 +313,53 @@ describe('Runner', function () {
...
+                });
+
+            run
+                .then(function () {
+                    done();
+                })
+                .catch(done);
+        });
+
+        it('Should raise exception if all tests are rejected by filter', function (done) {
```
Comment (VasilyStrelyaev) [inline test/server/runner-test.js]: an exception

File: test/server/runner-test.js [hunk 16]
```diff
@@ -325,4 +437,39 @@ describe('Runner', function () {
             testFilter(filter, expectedTestNames, done);
         });
     });
+
+    describe('.run()', function () {
+        it('Should raise exception if connection disconnected during tests', function (done) {
```
Comment (VasilyStrelyaev) [inline test/server/runner-test.js]: Should raise an exception if the connection breaks while tests are running

**Comment by AndreyBelym** [comment]
FPR

File: src/browser-connection/index.js [hunk 17]
```diff
@@ -34,12 +35,15 @@ export default class BrowserConnection extends EventEmitter {
         this.idleUrl      = `${gateway.domain}/browser/idle/${this.id}`;
         this.statusUrl    = `${gateway.domain}/browser/status/${this.id}`;
 
+        this.on('error', () => {
+            this.close();
+        });
```
Comment (inikulin) [inline src/browser-connection/index.js]:
```js
this.on('error', () => this.close());
```

File: src/browser-connection/index.js [hunk 18]
```diff
@@ -68,7 +72,8 @@ export default class BrowserConnection extends EventEmitter {
     }
 
     close () {
-        this.ready = false;
+        this.disconnected = true;
+        this.ready        = false;
```
Comment (inikulin) [inline src/browser-connection/index.js]: New line after variable assignments

File: src/runner/bootstrapper.js [hunk 19]
```diff
@@ -74,6 +74,14 @@ export default class Bootstrapper {
         if (!this.browsers.length)
             throw new Error(getText(MESSAGE.browserNotSet));
 
+        var disconnectedUserAgents = this.browsers
+            .filter(browser => browser instanceof BrowserConnection &&
+                               browser.disconnected)
+            .map(bc => bc.userAgent);
+
+        if (disconnectedUserAgents.length)
+            throw new Error(getText(MESSAGE.cantRunAgainstDisconnectedBrowsers, disconnectedUserAgents.join(', ')));
```
Comment (inikulin) [inline src/runner/bootstrapper.js]: Looks good now, maybe we should refactor this to the separate function?

File: test/server/runner-test.js [hunk 20]
```diff
@@ -248,6 +184,54 @@ describe('Runner', function () {
                 })
                 .catch(done);
         });
+
+        it('Should not create a new local browser connection if sources are empty', function (done) {
```
Comment (inikulin) [inline test/server/runner-test.js]: It should be in `.run()` as well.

File: test/server/runner-test.js [hunk 21]
```diff
@@ -248,6 +184,54 @@ describe('Runner', function () {
...
+                });
+
+            run
+                .then(function () {
+                    done();
+                })
+                .catch(done);
+        });
+
+        it('Should raise an error if all tests are rejected by the filter', function (done) {
```
Comment (inikulin) [inline test/server/runner-test.js]: This should be in `.filter()`

File: test/server/runner-test.js [hunk 22]
```diff
@@ -325,4 +309,140 @@ describe('Runner', function () {
...
+
+                    brokenConnection.emit('error', 'I have failed :(');
+                }
+            }, 200);
+
+            setTimeout( function () {
+                if (!interval.isNaN())
+                    clearInterval(interval);
+
+            }, this.timeout());
```
Comment (inikulin) [inline test/server/runner-test.js]: No need for this guard, mocha will automatically fail test if it will not pass withitn 2 sec.

**Comment by inikulin** [comment]
Overall, looks really good. Just some minor issues left.

**Comment by inikulin** [comment]
\r-

File: test/server/runner-test.js (hunk 22 above)
Comment (AndreyBelym) [inline test/server/runner-test.js]: And interval still be running, even after test failed, and process will not stop. We really need to clear the interval manually.

Comment (inikulin) [inline test/server/runner-test.js]: You can move `interval` var in upper scope (but rename it, so it's purpose will be clear)  and clean it in `afterEach`

Comment (AndreyBelym) [inline test/server/runner-test.js]: I found timedOut property in test context, it's better to use it IMHO.

Comment (AndreyBelym) [inline test/server/runner-test.js]: BTW, I'd not say that Mocha is well-documented :(

**Comment by AndreyBelym** [comment]
FPR

File: src/runner/bootstrapper.js (hunk 19 above)
Comment (inikulin) [inline src/runner/bootstrapper.js]: It' should be `_checkForDisconnectedBrowsers`

**Comment by inikulin** [comment]
Just single naming issue \r-

**Comment by AndreyBelym** [comment]
Travis messed with node 0.10 again
```
The command "eval npm install " failed. Retrying, 2 of 3.
npm WARN package.json @ No repository field.
npm WARN unmet dependency /home/travis/build/testcafe-build-bot/testcafe-phoenix/node_modules/del/node_modules/rimraf/node_modules/glob/node_modules/inflight requires once@'^1.3.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
```

**Comment by inikulin** [comment]
lgtm

**Comment by VasilyStrelyaev** [comment]
lgtm
